### PR TITLE
Default country from env

### PR DESCRIPTION
**Pull request by giosce**
I'm working on adopting public code by a large US organization. We will need more changes, this is a basic one.
My ideal approach is to have as much common code as possible and have country or organization customizations as much as possible in config files.

This change simply externalize the default language and country in the config file (.env) instead of being hardcoded in the codebase.

Happy to review/discuss this and other change ideas.

### CODE REVIEW

**Comment by bfabio** [comment]
@giosce lgtm, thanks! :rocket: 

Please keep in mind there's a big refactor in store at https://github.com/sebbalex/publiccode-editor/tree/refactor that touches the i18n part a lot

**Review by bfabio — APPROVED** [review]

**Comment by giosce** [comment]
> @giosce lgtm, thanks! 🚀
> 
> Please keep in mind there's a big refactor in store at https://github.com/sebbalex/publiccode-editor/tree/refactor that touches the i18n part a lot

Thanks @bfabio. Are you the best person to talk about upcoming changes? Is there a place like slack where some of us could discuss some changes?

**Comment by bfabio** [comment]
@giosce it's a team effort, but yes, we can talk about changes :)

Our Slack is at https://slack.developers.italia.it, channel #publiccode

**Comment by bfabio** [comment]
FYI, the refactoring is now at https://github.com/italia/publiccode-editor/tree/develop and this repo's default branch.

**Comment by bfabio** [comment]
The equivalent is already in `develop` with a different approach (2023769c3f7eb83894a3cda46067054605bb7387).

**Pull request closed without merging**
