### PR TITLE
Issue : #7

### PR DESCRIPTION
**Pull request by souravpd**
Fixed-Bug 
Added an Overflow property to the text-area content and added min-height and margin properties.
Suggestions Appreciated

### CODE REVIEW

**Comment by libremente** [comment]
Hi @souravpd and thanks for the PR! 
Personally, I believe that adding the `flex-flow` property may be a good temporary solution for #7.
For what concerns #39, we decided not to patch it for the moment since the problem is not showing up by using yarn and, most probably, the problem was related to a non-updated .lock file. 
If you revert the mods on `src/asset/editor_widget.scss` I can merge this PR and fix #7! :+1:

**Comment by souravpd** [comment]
Ya sure sir
I'll do it just now
Thanks for your feedback

**Comment by souravpd** [comment]
Updated the files as instructed

**Comment by libremente** [comment]
Thanks @souravpd , merged! :+1:

**Pull request merged**
